[window]

opacity = 0.7

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Light"
startup_mode = "Fullscreen"

[font]

normal.family = "0xProto Nerd Font Mono"
bold.family = "0xProto Nerd Font Mono"
italic.family = "0xProto Nerd Font Mono"
bold_italic.family = "0xProto Nerd Font Mono"

size = 15.0

